import { z } from "zod";
import { and, eq, isNull, gt } from "drizzle-orm";
import { PublicKey } from "@solana/web3.js";
import nacl from "tweetnacl";
import bs58 from "bs58";
import { cookies } from "next/headers";
import { route } from "@/server/route";
import { json, parseBody, rateLimit, assertSameOrigin, HttpError } from "@/server/http";
import { db, schema } from "@/server/db/client";
import { signSession, cookieOptions, WALLET_COOKIE } from "@/server/auth/session";
import { activeChain } from "@/lib/chain/chains";
import { isSolanaAddress, isSolanaSignature, signInMessage } from "@/lib/chain/solana";
export const dynamic = "force-dynamic";
const body = z.object({ address: z.string().refine(isSolanaAddress), origin: z.string().url(), nonce: z.string().regex(/^[a-f0-9]{48}$/), chainId: z.number().int(), signature: z.string().refine(isSolanaSignature) });
export const POST = route(async (req) => {
 rateLimit(req, "auth-verify", { limit: 20, windowSec: 60 }); assertSameOrigin(req);
 const input = await parseBody(req, body);
 if (input.origin !== req.headers.get("origin") || input.chainId !== activeChain().id) throw new HttpError(400, "Sign-in is for another site or network");
 const message = new TextEncoder().encode(signInMessage(input));
 if (!nacl.sign.detached.verify(message, bs58.decode(input.signature), new PublicKey(input.address).toBytes())) throw new HttpError(401, "Signature does not match the wallet");
 const [nonce] = await db().update(schema.authNonces).set({ usedAt: new Date() })
  .where(and(eq(schema.authNonces.nonce, input.nonce), isNull(schema.authNonces.usedAt), gt(schema.authNonces.expiresAt, new Date()))).returning();
 if (!nonce) throw new HttpError(400, "Sign-in nonce is invalid or expired");
 const { address, chainId } = input;
 await db().insert(schema.wallets).values({ address, lastChainId: chainId }).onConflictDoUpdate({ target: schema.wallets.address, set: { lastSeenAt: new Date(), lastChainId: chainId } });
 const ttl = 7 * 24 * 3600;
 const token = await signSession({ kind: "wallet", address, chainId }, ttl);
 (await cookies()).set(WALLET_COOKIE, token, cookieOptions(ttl));
 return json({ ok: true, address });
});
